### ISSUE TITLE
Seeding and Migrations

### ISSUE THREAD

**Issue by mythril** [Elhebert/dieterstinglhamber.me#10]
I was reading over:

https://github.com/Elhebert/dieterstinglhamber.me/blob/master/posts/2018-05-31.the-good-the-bad-and-the-ugly-of-seeding-data-in-production.md

And the proposed solution (mixing seeders and migrations) has an issue that is eating at me: seeders tend to change as the structure of the database changes, thus potentially becoming incompatible with their 'step' in the migration process. This is the reason why I choose to stick with doing production seeding in a migration script, and test seeding in a seeding script.

I want the test seeds to be easy to maintain and up to date, I want the migration scripts to be accurate representations of their era in the migration history.

Just my 2 cents, thanks for the article

**Comment by Elhebert** [comment]
Thanks for your feedback 👌

The way I see it is: "_Use migration for database structure and seeders for data seeding._"

But what I'm doing is the same as seeding from a migration, I just extract that part into a seeder that I call inside the migration, I feel like this is cleaner.

If you want to avoid mixing your test seeders with "production" seeders you can move them into another file. That way they won't be run when calling `php artisan db:seed`.

**Comment by mythril** [comment]
@Elhebert I must have overlooked the part where you explicitly called to the seeder scripts from the migration scripts, now I see that our solutions are equivalent, thank you for clarifying.
